const mongoose = require('mongoose')
const ObjId = mongoose.Types.ObjectId


const laptopSchema = new mongoose.Schema({
    name:{
        type:String
    },
    os:{
        type:String
    },
    price:{
        type:String
    },
    img_one:{
        type:String
    },
    img_two:{
        type:String
    },
    img_three:{
        type:String
    },
    img_four:{
        type:String
    },
    ram:{
        type:String
    },
    processor:{
        type:String
    },
    camera:{
        type:String
    },
    battery:{
        type:String
    },
    display:{
        type:String
    },
    launch_date:{
        type:String
    },
    // operating_system:String,
    custom_ui:String,
    chipset:String,
    cpu:String,
    architecture:String,
    graphics:{
        type:String
    },
    ram_type:{
        type:String
    },
    display_type:{
        type:String
    },
    screen_size:{
        type:String
    },
    resolution:{
        type:String
    },
    aspect_ratio:{
        type:String
    },
   
    screen_body_ratio:{
        type:String
    },
    screen_protection:{
        type:String
    },
    bezel_less_display:{
        type:String
    },
    touch_screen:{
        type:String
    },
    brightness:{
        type:String
    },
    refresh_rate:{
        type:String
    },
    height:{
        type:String
    },
    width:{
        type:String
    },
    thickness:{
        type:String
    },
    weight:{
        type:String
    },
    pixel_density:{
        type:String
    },
    colours:{
        type:String
    },
    waterproof:{
        type:String
    },
    battery_type:{
        type:String
    },
    battery_removable:{
        type:String
    },
    battery_time:{
        type:String
    },
    battery_backup:{
        type:String
    },
    SSD:{
        type:String
    },
    SSD_capacity:{
        type:String
    },
    HDD:{
        type:String
    },
    HDD_capacity:{
        type:String
    },
    network_support:{
        type:String
    },
    VoLTE:{
        type:String
    },
    wifi:{
        type:String
    },
    wifi_features:{
        type:String
    },
    bluetooth:{
        type:String
    },
    gps:{
        type:String
    },
    nfc:{
        type:String
    },
    usb_connectivity:{
        type:String
    },
    fm_radio:{
        type:String
    },
    loudspeaker:{
        type:String
    },
    audio_jack:{
        type:String
    },
    fingerprint_sensor:{
        type:String
    },
    fingerprint_sensor_position:{
        type:String
    },
    other_sensors:{
        type:String
    }
},{
    timestamps:true
})

const Laptop = mongoose.model('laptops',laptopSchema)

module.exports = Laptop